// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGkkm3fvXRdJisroNDj2VR55NXRpPAF74',
    appId: '1:537650473196:web:8010f5ba8fc4e6aab69dc9',
    messagingSenderId: '537650473196',
    projectId: 'crud-vehiculos',
    authDomain: 'crud-vehiculos.firebaseapp.com',
    storageBucket: 'crud-vehiculos.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYwMyPElJr3ZrogHjwzr9TMdanT-2kk2o',
    appId: '1:537650473196:android:a95e05ae8b5ddbbeb69dc9',
    messagingSenderId: '537650473196',
    projectId: 'crud-vehiculos',
    storageBucket: 'crud-vehiculos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA793h-0X4Y34JvRDBuFR0q8XljYTOZpnA',
    appId: '1:537650473196:ios:ba0b312befc4c1ebb69dc9',
    messagingSenderId: '537650473196',
    projectId: 'crud-vehiculos',
    storageBucket: 'crud-vehiculos.appspot.com',
    iosClientId: '537650473196-542s4fl4tfvjk806megu0e9q5trnvrqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.damU3VehiculosFirebase',
  );
}
